STORE_PATHS = {
    "ACTION_DB_PATH": "actions.db",
    "AUTHORING_DB_PATH": "authoring.db",
    "FEEDBACK_PATH": "feedback.jsonl",
    "HEARTBEAT_DB_PATH": "heartbeat.db",
    "HOME_EVENTS_DB_PATH": "home_events.db",
    "HOME_MODEL_DB_PATH": "home_model.db",
    "HOME_RECONCILE_DB_PATH": "home_reconcile.db",
    "GROOM_DB_PATH": "groom.db",
    "KNOWLEDGE_DB_PATH": "knowledge.db",
    "VEINS_PATH": "veins.json",
    "VEINS_D_PATH": "veins.d",
    "VEIN_ENGINE_DB_PATH": "vein_engine.db",
    "MEDIA_DB_PATH": "media.db",
    "PULSE_DB_PATH": "pulse.db",
    "SIGNALS_LOG_PATH": "signals_log.jsonl",
    "ANALYST_LOG_PATH": "analyst_log.jsonl",
    "RHYTHM_DB_PATH": "rhythm.db",
    "SCHEDULER_DB_PATH": "scheduler.db",
    "SERIES_DB_PATH": "series.db",
    "USER_PROFILE_DB_PATH": "user_profiles/store.db",
    "VERA_INTERESTS_DB_PATH": "vera_interests/store.db",
    "PROFILE_GRAPH_DB_PATH": "profile_graph/store.db",
    "EXTRACT_DB_PATH": "extract/cursors.db",
    "LEARN_DB_PATH": "learn/store.db",
    "VERA_JOURNAL_PATH": "journal/JOURNAL.md",
    "VERA_MEMORY_DIR": "vera_memory",
}
